/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sprint3;

public class App {
    public static void main(String[] args) {
        System.out.println("Bienvenido al Juego de Trivia!");
        System.out.println("Responde las siguientes preguntas seleccionando el numero de la opcion correcta");
        Quiz quiz = new Quiz();
        quiz.init();
        quiz.showQuestions();
    }
}
