/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sprint1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class AppTest {
    @Test
    void checkNumberInRange1_4(int numero){
        assertTrue(numero >= 1 && numero <= 4);
    }
}
