/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pc4postfecha.cc3s2;

public class Game {
    private Mapa mapa;
    public static void main(String[] args) {
        // Inicializamos el mapa
        Mapa mapa = new Mapa();
        //Player player = new Player();
        String userCommand;
        Wave wave = new Wave(0);

        // Construimos el mapa
        mapa.printMapa();
        // constructor
        

        do{
            CommandFactory commandFactory = new CommandFactory();
            System.out.println("Ingrese un comando: \n" +
                    "1. START_WAVE\n" +
                    "2. PLACE_TOWER TYPE_TOWER x y\n" +
                    "3. VIEW_MAP\n" +
                    "4. exit\n");
            userCommand = System.console().readLine();
            if (userCommand.equals("START_WAVE")) {
                wave.startWave();
                mapa.printMapa();
            }
            else if (userCommand.startsWith("PLACE_TOWER")) {
                // PLACE_TOWER Cannon 3 4
                String[] command = userCommand.split(" ");
                commandFactory.execute(command);
            }
            else if (userCommand.equals("VIEW_MAP")) {
                mapa.printMapa();
            }
        }while (!userCommand.equals("exit"));
    }
    public void placeTower(Tower tower, int x, int y) {
        if (mapa.isValidPosition(x, y)) {
            mapa.placeTower(tower, x, y);
        }
    }
}
